In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

In [ ]:
# This is a Data cleaning project carried out in Python 2 by Emmanuel Echa. I am very aware of the myriad of libraries
# that comes with using Python 3, but not withstanding, I started from the rudiments of Python 2 to get familiar
# with its far surpasing libraries and its legacy framework that will be referenced for a long time to come.

# Python 3 on the other hand will be easy to migrate to as the syntax between Python 2 and 3 remains the same with
# only few changes which will be encountered along the process of migration for a Data Scientist. 

# The data that is used for this data cleaning project contains 5000+ movie data scraped from IMDB website.
# This project is not based on a competition motive, but for educational purposes and referencing for the public 
# space.
# The data is being exported to a csv format, and it contains information on the actors, directors, budget, and gross, 
# as well as the IMDB rating and release year.

In [12]:
# By default, pandas and numpy has been imported by the Kaggle environment, but we need other libraries for full
# efficiency of python to clean the data to a reasonable state.

import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [13]:
# At this point, we will read the data '5000_movie_data.csv' that we will be cleaning for this exercise.
# NOTE! Before you start typing in codes for the panda read function, use the topmost button to your right hand side
# which is labelled 'Add Dataset', this creates a folder of the files that you will be working on. 
# This folder location is referenced as .../input/filename.

data = pd.read_csv("../input/5000_movie_data.csv")

In [14]:
# With the .head() method, we can view the first 5 indexed row of the data structure of the 5000_movie dataset by
# default. 

data.head()

   color         ...          movie_facebook_likes
0  Color         ...                         33000
1  Color         ...                             0
2  Color         ...                         85000
3  Color         ...                        164000
4    NaN         ...                             0

[5 rows x 28 columns]

In [19]:
# With Pandas, we can initiate some selction and slicing techniques to give us more insight into our dataset.
# We will run through 3 of them for more clarification.

# 1. data['movie_title']: This gives us a list of the first 20 movie titles indexed from 0 to 19.
# 2. data['director_name']: This gives us a list of the first 20 movies' director's names indexed from 0 to 19.
# 3. data['duration'][:12]: This selects a list of the first 12 movies' and their duration of play.

# The code below merges all the methods into one line of code to select multiple columns at once for display.

data[['movie_title','director_name','duration']][:20]

                                          movie_title   ...    duration
0                                             Avatar    ...       178.0
1           Pirates of the Caribbean: At World's End    ...       169.0
2                                            Spectre    ...       148.0
3                              The Dark Knight Rises    ...       164.0
4   Star Wars: Episode VII - The Force Awakens    ...   ...         NaN
5                                        John Carter    ...       132.0
6                                       Spider-Man 3    ...       156.0
7                                            Tangled    ...       100.0
8                            Avengers: Age of Ultron    ...       141.0
9             Harry Potter and the Half-Blood Prince    ...       153.0
10                Batman v Superman: Dawn of Justice    ...       183.0
11                                  Superman Returns    ...       169.0
12                                 Quantum of Solace    ...       106.0
13        Pirates of the Caribbean: Dead Man's Chest    ...       151.0
14                                   The Lone Ranger    ...       150.0
15                                      Man of Steel    ...       143.0
16          The Chronicles of Narnia: Prince Caspian    ...       150.0
17                                      The Avengers    ...       173.0
18       Pirates of the Caribbean: On Stranger Tides    ...       136.0
19                                    Men in Black 3    ...       106.0

[20 rows x 3 columns]

In [31]:
# The code segment below displays the first 5 movies that are over 120 mins long.

data[data['duration']> 120][:5]

   color         ...          movie_facebook_likes
0  Color         ...                         33000
1  Color         ...                             0
2  Color         ...                         85000
3  Color         ...                        164000
5  Color         ...                         24000

[5 rows x 28 columns]